#file: noinspection YAMLSchemaValidation, PluginYml
name: ${project.name}
author: ${project.organization.name}
version: ${project.version}
main: ${plugin.main}
api-version: '1.21.5'

commands:
  challenge:
    aliases:
      - randomDrops
      - randomDrop
    usage: /<command> <start/stop/toggleFail>
    description: Command to setting up your challenge.